package com.psms.enums;

public enum ActionType {
    LOGIN,
    SUBMIT_APP,
    UPDATE_STATUS,
    ASSIGN_STAFF, UPDATE_STAFF,
    CREATE_USER, UPDATE_USER, LOCK_USER, UNLOCK_USER, DELETE_USER,
    CREATE_SERVICE, UPDATE_SERVICE, TOGGLE_SERVICE, DELETE_SERVICE,
    CREATE_DEPT, UPDATE_DEPT, DELETE_DEPT,
    DELETE_DOC, UPLOAD_DOC,
    DELETE_LOG,
    EXPORT, IMPORT,
}
